name: Deploy 

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup & Lint
        run: |
          npm i
          npm run lint

      - name: Build Code
        run: |
          npm run build

      - name: Test code
        run: |
          npm run test

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
